### ISSUE TITLE
Alexa wont play any audio

### ISSUE THREAD

**Issue by metlock** [chucklapress/audio-alexa#1]
Everything tests fine in console, no errors logged in CW, But Alexa announces "their has been a problem with the skill" as soon as it tries to play my audio files. Any ideas?

**Comment by chucklapress** [comment]
Did you format the audio file and is it uploaded to S3 or are you selecting and actual playable audio link in the audioAsset.js file be sure that the audio files you are attempting to play are actually working, you can test this by taking the address of the link and putting it in the address bar and see if it plays audio. formatting configuration for audio alexa will play can be found here: https://developer.amazon.com/de/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html <https://developer.amazon.com/de/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html>   under the heading 
ffmpeg -i <input-file> -ac 2 -codec:a libmp3lame -b:a 48k -ar 16000 <output-file.mp3>

**Comment by metlock** [comment]
Audio file is on S3, plays back fine.
I was under the impression that you could use a higher bit rate, is it also limited to 90 seconds playback with this code? I'm trying to get a streaming audio solution up and running.

**Comment by chucklapress** [comment]
Your audio clip can be as long as you want my angel pod cast skill has audio clips over 1 hour in length each, but I have always converted the files using the ffmeg converter I mentioned in the previous email because when I haven’t I would experience your problem. Also make sure your files in s3 are flagged for public access

**Comment by chucklapress** [comment]
Did you get it sorted out?
